# Generated by Django 3.1.7 on 2021-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('destinatário', models.CharField(max_length=100)),
                ('mensagem', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'WhatsApp')], default=0)),
            ],
        ),
    ]
