# Generated by Django 3.1.7 on 2021-03-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao_agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='destinatário',
            new_name='destinatario',
        ),
    ]
