# Generated by Django 3.1.7 on 2021-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao_agendamento', '0002_auto_20210311_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='status',
            field=models.IntegerField(choices=[(0, 'Não Enviado'), (1, 'Enviado')], default=0),
        ),
    ]
