# Generated by Django 3.1.7 on 2021-03-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao_agendamento', '0004_auto_20210311_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['data_hora']},
        ),
        migrations.AlterModelTable(
            name='comunicado',
            table='solicitacao_agendamento_comunicado',
        ),
    ]
